/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    accounts: Account;
    users: User;
    media: Media;
    sites: Site;
    site_metrics_daily: SiteMetricsDaily;
    link_placements: LinkPlacement;
    alerts: Alert;
    alert_configs: AlertConfig;
    incidents: Incident;
    content_events: ContentEvent;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    site_metrics_daily: SiteMetricsDailySelect<false> | SiteMetricsDailySelect<true>;
    link_placements: LinkPlacementsSelect<false> | LinkPlacementsSelect<true>;
    alerts: AlertsSelect<false> | AlertsSelect<true>;
    alert_configs: AlertConfigsSelect<false> | AlertConfigsSelect<true>;
    incidents: IncidentsSelect<false> | IncidentsSelect<true>;
    content_events: ContentEventsSelect<false> | ContentEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    branding: Branding;
    network_defaults: NetworkDefault;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    branding: BrandingSelect<false> | BrandingSelect<true>;
    network_defaults: NetworkDefaultsSelect<false> | NetworkDefaultsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'ingest-gsc-site': TaskIngestGscSite;
      'ingest-ga4-site': TaskIngestGa4Site;
      'ingest-gsc': TaskIngestGsc;
      'ingest-ga4': TaskIngestGa4;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: number;
  name: string;
  google_oauth?: {
    google_email?: string | null;
    google_refresh_token?: string | null;
    google_access_token?: string | null;
    google_token_expiry?: string | null;
    google_connected_at?: string | null;
    google_scopes?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  account: number | Account;
  role: 'admin' | 'operator' | 'viewer';
  mfa_enabled?: boolean | null;
  last_login_at?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  account: number | Account;
  domain: string;
  status: 'active' | 'standby' | 'decommissioned' | 'redirected';
  niche: string;
  niche_group?: string | null;
  market: string;
  tier: '1' | '2' | '3' | '4' | '5';
  pinned?: boolean | null;
  launched_at?: string | null;
  successor_of?: (number | null) | Site;
  standby_for?: (number | null) | Site;
  hosting_provider?: string | null;
  notes?: string | null;
  external_ids?: {
    gsc_property?: string | null;
    ga4_property_id?: string | null;
    subaffiliate_tracking_id?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_metrics_daily".
 */
export interface SiteMetricsDaily {
  id: number;
  site: number | Site;
  date: string;
  clicks?: number | null;
  impressions?: number | null;
  ctr?: number | null;
  avg_position?: number | null;
  indexed_pages?: number | null;
  crawl_errors?: number | null;
  sessions?: number | null;
  engaged_sessions?: number | null;
  affiliate_clicks?: number | null;
  conversions?: number | null;
  revenue_eur?: number | null;
  uptime_pct?: number | null;
  lcp_ms?: number | null;
  inp_ms?: number | null;
  cls?: number | null;
  source_versions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "link_placements".
 */
export interface LinkPlacement {
  id: number;
  site: number | Site;
  target_url: string;
  source_domain: string;
  source_url?: string | null;
  anchor_text?: string | null;
  tier: '1' | '2' | '3' | '4' | '5';
  dr?: number | null;
  placed_at: string;
  status: 'live' | 'pending' | 'lost' | 'replaced';
  kind?: ('guest_post' | 'link_insert' | 'press_release' | 'editorial' | 'forum_social' | 'directory') | null;
  cost_eur?: number | null;
  verified_at?: string | null;
  notes?: string | null;
  redirect_replacement?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alerts".
 */
export interface Alert {
  id: number;
  site: number | Site;
  kind: 'indexation_drop' | 'ranking_collapse' | 'manual_action' | 'traffic_anomaly' | 'link_velocity' | 'uptime_cwv';
  severity: 'critical' | 'warning' | 'info';
  status: 'open' | 'acknowledged' | 'resolved';
  triggered_at: string;
  acknowledged_at?: string | null;
  acknowledged_by?: (number | null) | User;
  resolved_at?: string | null;
  signal?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  note?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alert_configs".
 */
export interface AlertConfig {
  id: number;
  site?: (number | null) | Site;
  kind: 'indexation_drop' | 'ranking_collapse' | 'manual_action' | 'traffic_anomaly' | 'link_velocity' | 'uptime_cwv';
  enabled?: boolean | null;
  threshold?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incidents".
 */
export interface Incident {
  id: number;
  site: number | Site;
  title: string;
  started_at: string;
  resolved_at?: string | null;
  outcome?: ('recovered' | 'failed_over' | 'decommissioned' | 'ongoing') | null;
  summary?: string | null;
  linked_alerts?: (number | Alert)[] | null;
  actions_taken?:
    | {
        description: string;
        at?: string | null;
        by?: string | null;
        id?: string | null;
      }[]
    | null;
  post_mortem?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content_events".
 */
export interface ContentEvent {
  id: number;
  site: number | Site;
  kind: 'generated' | 'updated' | 'pruned' | 'editorial';
  count: number;
  at: string;
  template?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'ingest-gsc-site' | 'ingest-ga4-site' | 'ingest-gsc' | 'ingest-ga4';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'ingest-gsc-site' | 'ingest-ga4-site' | 'ingest-gsc' | 'ingest-ga4') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'accounts';
        value: number | Account;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'site_metrics_daily';
        value: number | SiteMetricsDaily;
      } | null)
    | ({
        relationTo: 'link_placements';
        value: number | LinkPlacement;
      } | null)
    | ({
        relationTo: 'alerts';
        value: number | Alert;
      } | null)
    | ({
        relationTo: 'alert_configs';
        value: number | AlertConfig;
      } | null)
    | ({
        relationTo: 'incidents';
        value: number | Incident;
      } | null)
    | ({
        relationTo: 'content_events';
        value: number | ContentEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  name?: T;
  google_oauth?:
    | T
    | {
        google_email?: T;
        google_refresh_token?: T;
        google_access_token?: T;
        google_token_expiry?: T;
        google_connected_at?: T;
        google_scopes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  account?: T;
  role?: T;
  mfa_enabled?: T;
  last_login_at?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  account?: T;
  domain?: T;
  status?: T;
  niche?: T;
  niche_group?: T;
  market?: T;
  tier?: T;
  pinned?: T;
  launched_at?: T;
  successor_of?: T;
  standby_for?: T;
  hosting_provider?: T;
  notes?: T;
  external_ids?:
    | T
    | {
        gsc_property?: T;
        ga4_property_id?: T;
        subaffiliate_tracking_id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_metrics_daily_select".
 */
export interface SiteMetricsDailySelect<T extends boolean = true> {
  site?: T;
  date?: T;
  clicks?: T;
  impressions?: T;
  ctr?: T;
  avg_position?: T;
  indexed_pages?: T;
  crawl_errors?: T;
  sessions?: T;
  engaged_sessions?: T;
  affiliate_clicks?: T;
  conversions?: T;
  revenue_eur?: T;
  uptime_pct?: T;
  lcp_ms?: T;
  inp_ms?: T;
  cls?: T;
  source_versions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "link_placements_select".
 */
export interface LinkPlacementsSelect<T extends boolean = true> {
  site?: T;
  target_url?: T;
  source_domain?: T;
  source_url?: T;
  anchor_text?: T;
  tier?: T;
  dr?: T;
  placed_at?: T;
  status?: T;
  kind?: T;
  cost_eur?: T;
  verified_at?: T;
  notes?: T;
  redirect_replacement?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alerts_select".
 */
export interface AlertsSelect<T extends boolean = true> {
  site?: T;
  kind?: T;
  severity?: T;
  status?: T;
  triggered_at?: T;
  acknowledged_at?: T;
  acknowledged_by?: T;
  resolved_at?: T;
  signal?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alert_configs_select".
 */
export interface AlertConfigsSelect<T extends boolean = true> {
  site?: T;
  kind?: T;
  enabled?: T;
  threshold?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incidents_select".
 */
export interface IncidentsSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  started_at?: T;
  resolved_at?: T;
  outcome?: T;
  summary?: T;
  linked_alerts?: T;
  actions_taken?:
    | T
    | {
        description?: T;
        at?: T;
        by?: T;
        id?: T;
      };
  post_mortem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content_events_select".
 */
export interface ContentEventsSelect<T extends boolean = true> {
  site?: T;
  kind?: T;
  count?: T;
  at?: T;
  template?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding".
 */
export interface Branding {
  id: number;
  product_name: string;
  customer_tag?: string | null;
  primary_color?: string | null;
  dark_color?: string | null;
  soft_color?: string | null;
  logo_initials?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "network_defaults".
 */
export interface NetworkDefault {
  id: number;
  default_alert_thresholds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Days between content refresh cycles
   */
  content_refresh_cadence?: number | null;
  link_velocity_bands?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding_select".
 */
export interface BrandingSelect<T extends boolean = true> {
  product_name?: T;
  customer_tag?: T;
  primary_color?: T;
  dark_color?: T;
  soft_color?: T;
  logo_initials?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "network_defaults_select".
 */
export interface NetworkDefaultsSelect<T extends boolean = true> {
  default_alert_thresholds?: T;
  content_refresh_cadence?: T;
  link_velocity_bands?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskIngest-gsc-site".
 */
export interface TaskIngestGscSite {
  input: {
    accountId: number;
    siteId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskIngest-ga4-site".
 */
export interface TaskIngestGa4Site {
  input: {
    accountId: number;
    siteId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskIngest-gsc".
 */
export interface TaskIngestGsc {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskIngest-ga4".
 */
export interface TaskIngestGa4 {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}